POST http://localhost:3002/api/v1/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWJjMzZiNC1mYTc2LTQxOTMtYjBhOC0zZmU2ZDExZjQ1Y2IiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzYzMjQzMywiZXhwIjoxNzQzNjM2MDMzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.eOlABPB9Ba4MS_JG30IKkDNRq3eSkwlJw3RAoWFSwvw

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Jack jeans
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

4000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="discount"

15
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

jean
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dressStyle"

outdoor
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="clothType"

trouser
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="material"

jean
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="brand"

nike
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="shortDescription"

Comfortable and stylish Nike t-shirt for everyday wear
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="longDescription"

A premium cotton t-shirt from Nike, perfect for casual outings. Soft, breathable, and designed for comfort.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[0][color]"

red
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[0][size]"

XL
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[0][quantity]"

50
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[0][images]"; filename="test-image-4.png"
Content-Type: image/png

< ./test-image-4.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[0][images]"; filename="test-image-5.png"
Content-Type: image/png

< ./test-image-5.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[1][color]"

Grey
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[1][size]"

L
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[1][quantity]"

30
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="variants[1][images]"; filename="test-image-6.png"
Content-Type: image/png

< ./test-image-6.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--