DELETE http://localhost:3002/api/v1/products/1c1d110b-b854-4b12-9c98-028d50729194
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWJjMzZiNC1mYTc2LTQxOTMtYjBhOC0zZmU2ZDExZjQ1Y2IiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzMyODEyMSwiZXhwIjoxNzQzMzMxNzIxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.Yh0wRgQb5FcYEjra_ndtKjOoiI9HRar-xiJzbip7c_U