GET http://localhost:3002/api/v1/payments?userId=52c8cfeb-897f-46d7-8b75-7a7c5ba01da1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWJjMzZiNC1mYTc2LTQxOTMtYjBhOC0zZmU2ZDExZjQ1Y2IiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NDAzNzc3MSwiZXhwIjoxNzQ0MDQxMzcxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.AHU6obaLGX41ED-GRa--QSdDAe48dszIuMz0j3IljxQ