POST http://localhost:3002/api/v1/product-variants/check-availability
Content-Type: application/json

{
     "products": [
        {
            "productId": "0fbdbc3e-3046-412d-ab05-e1f5b0331239",
            "variants": [
                {
                    "id": "340f380d-3d81-4d76-acf9-15caf0b47ce2",
                    "color": "Grey",
                    "size": "L",
                    "quantity": 3
                },
                 {
                    "id": "823e9f00-a69b-4de8-b872-c97bf5f250a6",
                    "color": "Green",
                    "size": "L",
                    "quantity": 1
                }
            ]
        },
         {
            "productId": "9bcffcbd-4455-4661-a15b-972626c2f5b0",
            "variants": [
                {
                    "id": "a60202f2-fa73-40db-b9a5-48dbb847a273",
                    "color": "Grey",
                    "size": "L",
                    "quantity": 1
                },
                 {
                    "id": "d60fa9bb-67a4-4f70-a361-b9b20f5a68b9",
                    "color": "red",
                    "size": "XL",
                    "quantity": 4
                }
            ]
        }
    ]
}