GET http://localhost:3002/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YzIyMjdmNS0zM2JlLTQ5NTQtODczMy1iYzJkZDlhYzBkMGQiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzA2NzY1MCwiZXhwIjoxNzQzMDcxMjUwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.FEymqGH54XiTicUepEeLV6ET9WU1s-_rTEKTQADRGhM


GET http://localhost:3002/api/v1/users/4c2227f5-33be-4954-8733-bc2dd9ac0d0d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YzIyMjdmNS0zM2JlLTQ5NTQtODczMy1iYzJkZDlhYzBkMGQiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzA2NzY1MCwiZXhwIjoxNzQzMDcxMjUwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.FEymqGH54XiTicUepEeLV6ET9WU1s-_rTEKTQADRGhM