PATCH http://localhost:3002/api/v1/bank-transfers/293b78aa-ff07-42d3-8807-2027cf15925e/confirm-transfer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWJjMzZiNC1mYTc2LTQxOTMtYjBhOC0zZmU2ZDExZjQ1Y2IiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NDAzMDIyOSwiZXhwIjoxNzQ0MDMzODI5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.Y15xXMk4v6nhRKdPoupoM5lle8cXmyOgxjOKDofLinY