POST http://localhost:3002/api/v1/reviews
Content-Type: application/json

{
    "reviewer": "Ejim Favour",
    "review": "I really loved the product",
    "stars": 4,
    "productId": "36317226-16e8-4e67-ad34-989ae70a578d"
}