DELETE http://localhost:3002/api/v1/reviews/c74ea638-d6b8-4e73-a46d-c19dd419a7d8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWJjMzZiNC1mYTc2LTQxOTMtYjBhOC0zZmU2ZDExZjQ1Y2IiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzM0ODU1NiwiZXhwIjoxNzQzMzUyMTU2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.-boI2cPnoAWCRfBxtHPoCNWmyWeDQVrJsVoBtu2HDuE
