GET http://localhost:3002/api/v1/orders?userId=52c8cfeb-897f-46d7-8b75-7a7c5ba01da1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWJjMzZiNC1mYTc2LTQxOTMtYjBhOC0zZmU2ZDExZjQ1Y2IiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NDAzMzg5MiwiZXhwIjoxNzQ0MDM3NDkyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.Tlrmue39AQm6J0chO6J4wUy3tbSu6a1PJaJTyHVy6z0