POST http://localhost:3002/api/v1/paystack/initiate-payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MmM4Y2ZlYi04OTdmLTQ2ZDctOGI3NS03YTdjNWJhMDFkYTEiLCJlbWFpbCI6ImZhdm91cmVqaW01NkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDQ3NzQ4NSwiZXhwIjoxNzQ0NDgxMDg1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.nukF_wJabrOvDxsul1MlZXHm4HJ-RhHrDlp10MNuex4

{
    "deliveryPicker": "Ejim Favour",
    "deliveryAddress": "Lekki phase 1, Lagos",
    "discountId": "f9e23267-239d-4745-b30b-30f6ce64f384",
    "products": [
        {
            "productId": "02598945-2a25-4fbf-af04-7715a0851be5",
            "price": 45000,
            "variants": [
                {
                    "id": "14e74931-804e-4c99-a73b-2a1cfcf06f2d",
                    "color": "Lime",
                    "size": "M",
                    "quantity": 2
                },
                 {
                    "id": "37825878-78e0-403c-a82b-e163c1afb8b3",
                    "color": "Navy",
                    "size": "S",
                    "quantity": 1
                }
            ]
        },
         {
            "productId": "8f3ef9c1-da6a-4b39-9250-914f9b2dbb30",
            "price": 32000,
            "variants": [
                {
                    "id": "5ecc9ac0-2e29-47ca-9970-3b02ac3aef7c",
                    "color": "Black",
                    "size": "S",
                    "quantity": 1
                },
                 {
                    "id": "6a9d6ef6-7707-40b6-9271-6c87d9c48a6a",
                    "color": "Black",
                    "size": "M",
                    "quantity": 4
                }
            ]
        }
    ]
}